name: Github Page Deployment
on:
  push:
    branches:
      - 'github-actions'
jobs:
  auto_deploy_gae:
    permissions: write-all
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist